# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '注册.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 638)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        Form.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 60, 321, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.name = QtWidgets.QLineEdit(self.layoutWidget)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.okpassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.okpassword.setToolTip("")
        self.okpassword.setObjectName("okpassword")
        self.verticalLayout.addWidget(self.okpassword)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addnew = QtWidgets.QPushButton(self.layoutWidget)
        self.addnew.setObjectName("addnew")
        self.horizontalLayout.addWidget(self.addnew)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.quitit = QtWidgets.QPushButton(self.layoutWidget)
        self.quitit.setObjectName("quitit")
        self.horizontalLayout.addWidget(self.quitit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户注册页面"))
        self.label_2.setText(_translate("Form", "姓名："))
        self.label.setText(_translate("Form", "用户名："))
        self.label_3.setText(_translate("Form", "密码："))
        self.label_4.setText(_translate("Form", "再次输入密码："))
        self.label_5.setText(_translate("Form", "注册类型："))
        self.comboBox.setItemText(0, _translate("Form", "学生"))
        self.comboBox.setItemText(1, _translate("Form", "管理员"))
        self.comboBox.setItemText(2, _translate("Form", "老师"))
        self.addnew.setText(_translate("Form", "注册"))
        self.quitit.setText(_translate("Form", "退出"))
