# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '登录页面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(696, 461)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        Form.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 180, 361, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.usersedit = QtWidgets.QLineEdit(self.layoutWidget)
        self.usersedit.setObjectName("usersedit")
        self.horizontalLayout.addWidget(self.usersedit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(296, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pwdetid = QtWidgets.QLineEdit(self.layoutWidget)
        self.pwdetid.setObjectName("pwdetid")
        self.horizontalLayout_2.addWidget(self.pwdetid)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.login = QtWidgets.QPushButton(self.layoutWidget)
        self.login.setAutoRepeatInterval(200)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        spacerItem2 = QtWidgets.QSpacerItem(17, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.registerbt = QtWidgets.QPushButton(self.layoutWidget)
        self.registerbt.setObjectName("registerbt")
        self.horizontalLayout_3.addWidget(self.registerbt)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.changebt = QtWidgets.QPushButton(self.layoutWidget)
        self.changebt.setObjectName("changebt")
        self.horizontalLayout_3.addWidget(self.changebt)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.quitbt = QtWidgets.QPushButton(self.layoutWidget)
        self.quitbt.setObjectName("quitbt")
        self.horizontalLayout_3.addWidget(self.quitbt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.namelabel = QtWidgets.QLabel(Form)
        self.namelabel.setGeometry(QtCore.QRect(229, 33, 441, 91))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(20)
        self.namelabel.setFont(font)
        self.namelabel.setObjectName("namelabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密  码："))
        self.login.setText(_translate("Form", "登录"))
        self.registerbt.setText(_translate("Form", "注册"))
        self.changebt.setText(_translate("Form", "用户管理"))
        self.quitbt.setText(_translate("Form", "退出"))
        self.namelabel.setText(_translate("Form", "登录系统"))
